version: '3.7'

services:
  db:
    image: 10.0.0.22:8082/postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-network

  web:
    image: 10.0.0.22:8083/repository/docker-host/python-fastapi:latest
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - fastapi-network

networks:
  fastapi-network:

volumes:
  postgres_data:
